_target_ : policy.IPA_full.IPA_full
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch
bandit_alg: BayesUCB
conf_bound : '1/t' #for KL_UCB
tie_breaking_eps : 1e-3
name : IPA-full

is_reward_known : False
is_cost_known : False
min_sample_required : 0
# prior : ['beta',['linear',1,2],['fixed',1]]
stopping_criteria : null
include_arm0 : True