_target_ : policy.TS_aDir_cave.TS_alpha_Dirichlet_increment_concave
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch

bandit_alg: TS-aDirichlet-increment-concave
name : IPA-full

is_reward_known : False
is_cost_known : False #True

refit_step : 100 #adaptive-log10
refit_max_round_1step : 100 #20 
refit_max_round_step : 2000

min_sample_required : 0
stopping_criteria : null
include_arm0 : True

pymc_draws : 2000 #500
pymc_tune : 1000 #1000
pymc_cores : 1
pymc_chains : 1

need_endpoint_dist : True