_target_ : policy.TS_MMLE.TS_Monotone_MLE
type_arm : participation-based
num_cost_learning : log2T
cost_alg : MultiBinSearch
bandit_alg: TS-MMLE
name : IPA-full
is_reward_known : False
is_cost_known : False #True
min_sample_required : 0 #3
stopping_criteria : null
include_arm0 : True