defaults:
  - _self_
  - setting : MABA_10CaveUni #left
  - policy : TS #IPA_full #longEU
  - reward_generator : bernoulli_cave_rand #dir #bernoulli_bounded_log #poly #bounded_log #mono_logistic
num_sim : 10
max_round : 10000
wandb_mode : online