defaults:
  - _self_
  - setting : MASA
  - agent : logit_MDM10_s001_6
  - policy : gEU2 #TS_EU2
  - model : logit
  - reward_generator : MASA_ber10_6
num_sim : 10
max_round : 1000
wandb_mode : online