_target_ : MABA_model.MABA_model
num_agent : 5 #provide practically uniform dist over increasing func
agent_cost : [0.1668,0.1668,0.1668,0.1668,0.1668]
type : fixed-best-arm
best_arm : 1 
init_seed_id : 0